### ISSUE TITLE
xcaddy build doesn't use replacements from go.mod

### ISSUE THREAD

**Issue by NullOranje** [caddyserver/xcaddy#141]
I have a project with the following structure, where `mycaddyplugin` imports some code from the main `myapp`

```
src/
 |-- myapp/
 |-- mycaddyplugin/
```

If I call `xcaddy run` from the `mycaddyplugin` folder, builds and runs as expected.  If I call `xcaddy build -with mycaddyplugin=.` from the same path, the build fails because the replace directive from `mycaddyplugin/go.mod` is not being carried over.

Is there something I'm missing when calling `xcaddy build`?

``` 
xcaddy version
v0.3.3 h1:0TdKXGl1u6Fc0Duc4qG0zu/aMyU/cTYgoXrvTkMeSnY=
```

**Comment by francislavoie** [comment]
That's unfortunately just how Go modules work, it's nothing specific to xcaddy. You can use additional `--with` to replace the packages you need though.

**Comment by mholt** [comment]
Both generate a new go.mod. Go modules work by applying replacements for the current module only, not any of its dependencies. (This can be somewhat annoying, for example when I develop `acmez` and I want to use it in Caddy, I have to put a replace in `caddy`, and the same replace in `certmagic`, in order to successfully use the custom local `acmez`.)

**Comment by NullOranje** [comment]
Yeah, this is exactly what I'm running into.   I just took the advice under the [Pro Tip](https://github.com/caddyserver/xcaddy#warning-pro-tip) and made a custom `main.go` so I can better manage the process.  Thanks!
