### ISSUE TITLE
404 - github.com/caddyserver/caddy/v2

### ISSUE THREAD

**Issue by jakubCF** [caddyserver/xcaddy#147]
Hi,
while trying to compile caddy with cloudflare module, it seems to hang on /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2

if I enter this url to my browser I get 404.

Is it just me or did they change v2 folder and everything is now broken?

**Comment by francislavoie** [comment]
Go module paths are not web URLs and can't be used as such, even if they look like they would be. `/v2` is for fetching from releases tagged v2.x.x and is needed because we had a - v1 which would conflict.

How long did you wait when it hanged? It was probably just in the middle of downloading. Try again and wait longer.

**Comment by jakubCF** [comment]
Thank you. Waiting little longer helped.
Sorry for bothering.
