### ISSUE TITLE
Add --help flag

### ISSUE THREAD

**Issue by henrywallace** [caddyserver/xcaddy#40]
I was reading how to compile a new local caddy module into a caddy docker image: https://hub.docker.com/_/caddy?tab=description. The examples on that page don't mention the local syntax as described in this repo's README. My first thought was to `docker run caddy:2-builder xcaddy --help` or `docker run caddy:2-builder xcaddy help` to learn the syntax. However those commands yield:
```
go list -m: not using modules
2020/11/15 18:29:25 [ERROR] exec [go list -m]: exit status 1:

```

It would be useful to have a help flag or subcommand to also show the helpful incantations as described in the README.

**Comment by mholt** [comment]
I am not sure there is room for a flag, because `xcaddy` is just a wrapper over the `caddy` command (technically, it wraps `go` commands but the `xcaddy` CLI is basically a wrapper for the `caddy` CLI). In other words, except for `xcaddy build`, `xcaddy` has the same CLI as `caddy`. If we add flags, you can't use those flags with the wrapped `caddy` command, which could be problematic, especially a help flag, which is often used when debugging modules.

Closing, but feel free to continue discussion if needed!
