### ISSUE TITLE
feature: handling replace clauses in plugins passed with --with

### ISSUE THREAD

**Issue by greenpau** [caddyserver/xcaddy#79]
@mholt , [by design](https://github.com/golang/go/issues/38665#issuecomment-620189068) the `replace` directives are not being considered.

For example the replace `go.mod`:

```
module github.com/greenpau/caddy-git

go 1.16

require (
        github.com/caddyserver/caddy/v2 v2.4.6
        github.com/go-git/go-git/v5 v5.4.2
        github.com/google/go-cmp v0.5.6
        go.uber.org/zap v1.20.0
)

replace github.com/go-git/go-git/v5 v5.4.2 => /home/greenpau/dev/go/src/github.com/go-git/go-git
```

The `replace` in plugin's `go.mod` will not be accounted for when compiling in `xcaddy`.

What do you think about parsing `go.mod` files in the plugin's passed with `--with` for the presence of `replace` clauses and adding them to the build?

**Comment by greenpau** [comment]
I can actually pass non-plugin package `--with github.com/go-git/go-git/v5@v5.4.2=/home/greenpau/dev/go/src/github.com/go-git/go-git` and it works. Thought reading the `go.mod` might be more convenient.

**Comment by greenpau** [comment]
A potential place to analyze the plugins' `go.mod` files is here:

https://github.com/caddyserver/xcaddy/blob/c8b2d00673f0c6f7b8c3a71e2713e6c981226639/environment.go#L111-L120

**Comment by francislavoie** [comment]
I think your `--with` with the replacement is the intended way to do this. I don't think we should add complexity by reading `go.mod` files. That's a lot.

**Comment by mholt** [comment]
The problem with reading go.mod is that there's a couple sources of truth: command line or go.mod, and plus sometimes you want to do a custom build without changing files on disk / in the repo, so your working copy is clean. That's why I opted for a solely command-line-based solution for simple custom builds, at least. It's automating the process of creating a new module with a go.mod file and then running build, so having to edit go.mod would be a little bit redundant. If you're already creating/editing go.mod you don't really need xcaddy.
